flowchart TD
    v1_start(["Start AdminDeleteAccountFrame.handleLogout"])
    v1_end(["End AdminDeleteAccountFrame.handleLogout"])
    v1_a["User chooses a navigation action"]
    v1_b["Open the login page"]
    v1_start --> v1_a
    v1_a --> v1_b
    v1_b --> v1_end
