flowchart TD
    v1_start(["Start LoginFrame.handleCreateAccount"])
    v1_end(["End LoginFrame.handleCreateAccount"])
    v1_a["User chooses a navigation action"]
    v1_b["Open the registration page"]
    v1_start --> v1_a
    v1_a --> v1_b
    v1_b --> v1_end
