flowchart TD
    v1_start(["Start AdminHomeFrame.handleViewAccounts"])
    v1_end(["End AdminHomeFrame.handleViewAccounts"])
    v1_a["User chooses a navigation action"]
    v1_b["Open the admin view account page"]
    v1_start --> v1_a
    v1_a --> v1_b
    v1_b --> v1_end
