flowchart TD
    v1_start(["Start UserHomeFrame.handleTransaction"])
    v1_end(["End UserHomeFrame.handleTransaction"])
    v1_a["User chooses a navigation action"]
    v1_b["Open the user transaction page"]
    v1_start --> v1_a
    v1_a --> v1_b
    v1_b --> v1_end
